### ISSUE TITLE
Any other settings on OpenERP

### ISSUE THREAD

**Issue by zzolo** [FreeGeekTwinCities/portero#21]
I recently notices that I needed to check a box to get this all working.
https://github.com/FreeGeekTwinCities/portero#run-openerp-server

Is there anything else that needs to be configured to get Porterp and OpenERP working?

**Comment by bdunnette** [comment]
No, I think the "track attendance for all employees" was the only setting that absolutely needs to be changed for Portero to function; sorry for not noting that "gotcha" sooner, it tripped me up as well!

**Comment by zzolo** [comment]
Thanks, Brian.  Just wanted to make sure as I am still having issue getting my local instance to track time correctly.
